# Activate explicitly with --spring.profiles.active=local
spring.datasource.url=jdbc:h2:file:./local-data/byr
spring.datasource.username=sa
spring.datasource.password=
file.storage.location=./local-data/images
app.public-base-url=http://localhost:8080
app.allowed-origins=http://localhost:3000
server.servlet.session.cookie.secure=false
